### ISSUE TITLE
Spreadsheet viewer has accessibility issues

### ISSUE THREAD

**Issue by qqmyers** [gdcc/dataverse-previewers#4]
Checking the spreadsheet viewer with Deque Axe, it reports several issues:

- [ ] Form elements must have labels (for the upper-left corner header)
- [ ] Table header text must not be empty (same element)
- [ ] Table headers in a data table must refer to data cells (corner header and row headers)
- [ ] All page content should be contained by landmarks (hidden div id=CopyPasteDiv added directly to the body)

These all appear to be problems with the HandsOnTable being used. A quick scan of their repo shows several recent accessibility issues logged, e.g. https://github.com/handsontable/handsontable/labels/Accessibility. It's not clear that these cover the issues above, but will probably mean changes are coming. We may want to look into submitting these issues and/or checking again as their issues are resolved.

**Comment by qqmyers** [comment]
I also hadn't realized that the Spreadsheet previewer loads v 0.28.4 and there are open source versions up through 11.0.1 - we should upgrade and test accessibility again. Any volunteers? I have not checked to see how much the API might have changed/how much work this might be.
